include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_final_fields: true
    use_super_parameters: true
    require_trailing_commas: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    sort_child_properties_last: false